book:
    title:            "GapBook"
    author:           "Cem Güler - cemguler@rpfusion.com"
    edition:          "Alpha"
    language:         tr
    publication_date: ~

    generator: { name: easybook, version: 5.0-DEV }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: dedication, content: dedication.md }
        - { element: introduction, content: intro.md }
        - { element: chapter, number: 1, content: what-is-phonegap.md }
        - { element: chapter, number: 2, content: js-toolbelt.md }
        - { element: chapter, number: 3, content: debugging.md }
        - { element: chapter, number: 4, content: networking.md }
        - { element: chapter, number: 5, content: location.md }
        - { element: chapter, number: 6, content: filesystem-storage-database.md }
        - { element: chapter, number: 7, content: accelerometer.md }
        - { element: chapter, number: 8, content: camera.md }
        - { element: chapter, number: 9, content: media.md }
        - { element: chapter, number: 10, content: native-events.md }
        - { element: chapter, number: 11, content: gestures.md }
        - { element: chapter, number: 12, content: contacts.md }
        - { element: chapter, number: 13, content: extending-phonegap-with-plugins.md }
        

        
    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            use_html_toc:   false
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
                            